/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { basicGetCompany } from "../../funcs/basicGetCompany.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetCompanyRequest$inboundSchema,
};

export const tool$basicGetCompany: ToolDefinition<typeof args> = {
  name: "basic-get-company",
  description:
    `Retrieve a company by its ID (\`companyId\`) or by a unique property (\`idProperty\`). You can specify what is returned using the \`properties\` query parameter.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await basicGetCompany(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
