/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { basicCreateContact } from "../../funcs/basicCreateContact.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.SimplePublicObjectInputForCreate$inboundSchema,
};

export const tool$basicCreateContact: ToolDefinition<typeof args> = {
  name: "basic-create-contact",
  description:
    `Create a single contact. Include a \`properties\` object to define [property values](https://developers.hubspot.com/docs/guides/api/crm/properties) for the contact, along with an \`associations\` array to define [associations](https://developers.hubspot.com/docs/guides/api/crm/associations/associations-v4) with other CRM records.`,
  scopes: ["write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await basicCreateContact(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
