/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { basicGetDeal } from "../../funcs/basicGetDeal.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetDealRequest$inboundSchema,
};

export const tool$basicGetDeal: ToolDefinition<typeof args> = {
  name: "basic-get-deal",
  description:
    `Read a Deal Object identified by \`{dealId}\`. \`{dealId}\` refers to the internal object ID by default, or optionally any unique property value as specified by the \`idProperty\` query param.  Control what is returned via the \`properties\` query param.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await basicGetDeal(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
