/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { basicGetProperties } from "../../funcs/basicGetProperties.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetPropertiesRequest$inboundSchema,
};

export const tool$basicGetProperties: ToolDefinition<typeof args> = {
  name: "basic-get-properties",
  description:
    `Get the list of all properties that are available on any hubspot object. Object types can be \`contacts\`, \`companies\`, or \`deals\`.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await basicGetProperties(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
