/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { basicCreateDeal } from "../../funcs/basicCreateDeal.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.SimplePublicObjectInputForCreate$inboundSchema,
};

export const tool$basicCreateDeal: ToolDefinition<typeof args> = {
  name: "basic-create-deal",
  description:
    `Create a deal with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard deals is provided.`,
  scopes: ["write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await basicCreateDeal(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
