/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { basicUpdateDeal } from "../../funcs/basicUpdateDeal.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateDealRequest$inboundSchema,
};

export const tool$basicUpdateDeal: ToolDefinition<typeof args> = {
  name: "basic-update-deal",
  description:
    `Perform a partial update of an Object identified by \`{dealId}\`. \`{dealId}\` refers to the internal object ID by default, or optionally any unique property value as specified by the \`idProperty\` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.`,
  scopes: ["write"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await basicUpdateDeal(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
