/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Basic } from "./basic.js";
import { Search } from "./search.js";

export class Hubspot extends ClientSDK {
  private _basic?: Basic;
  get basic(): Basic {
    return (this._basic ??= new Basic(this._options));
  }

  private _search?: Search;
  get search(): Search {
    return (this._search ??= new Search(this._options));
  }
}
