/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the mcp-hubspot SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx basicGetProperties.example.ts
 */

import { Hubspot } from "mcp-hubspot";

const hubspot = new Hubspot({
  hubspotToken: process.env["HUBSPOT_HUBSPOT_TOKEN"] ?? "",
});

async function main() {
  const result = await hubspot.basic.getProperties({
    objectType: "contacts",
  });

  console.log(result);
}

main().catch(console.error);
