/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateDealResponse =
  | components.SimplePublicObject
  | Uint8Array
  | string;

/** @internal */
export const CreateDealResponse$inboundSchema: z.ZodType<
  CreateDealResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.SimplePublicObject$inboundSchema, b64$.zodInbound]);

/** @internal */
export type CreateDealResponse$Outbound =
  | components.SimplePublicObject$Outbound
  | Uint8Array;

/** @internal */
export const CreateDealResponse$outboundSchema: z.ZodType<
  CreateDealResponse$Outbound,
  z.ZodTypeDef,
  CreateDealResponse
> = z.union([components.SimplePublicObject$outboundSchema, b64$.zodOutbound]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateDealResponse$ {
  /** @deprecated use `CreateDealResponse$inboundSchema` instead. */
  export const inboundSchema = CreateDealResponse$inboundSchema;
  /** @deprecated use `CreateDealResponse$outboundSchema` instead. */
  export const outboundSchema = CreateDealResponse$outboundSchema;
  /** @deprecated use `CreateDealResponse$Outbound` instead. */
  export type Outbound = CreateDealResponse$Outbound;
}

export function createDealResponseToJSON(
  createDealResponse: CreateDealResponse,
): string {
  return JSON.stringify(
    CreateDealResponse$outboundSchema.parse(createDealResponse),
  );
}

export function createDealResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateDealResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateDealResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateDealResponse' from JSON`,
  );
}
