/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The type of the object for which to retrieve properties.
 */
export const ObjectType = {
  Contacts: "contacts",
  Companies: "companies",
  Deals: "deals",
} as const;
/**
 * The type of the object for which to retrieve properties.
 */
export type ObjectType = ClosedEnum<typeof ObjectType>;

export type GetPropertiesRequest = {
  /**
   * The type of the object for which to retrieve properties.
   */
  objectType: ObjectType;
};

export type GetPropertiesResponse = { [k: string]: any } | Uint8Array | string;

/** @internal */
export const ObjectType$inboundSchema: z.ZodNativeEnum<typeof ObjectType> = z
  .nativeEnum(ObjectType);
/** @internal */
export const ObjectType$outboundSchema: z.ZodNativeEnum<typeof ObjectType> =
  ObjectType$inboundSchema;

/** @internal */
export const GetPropertiesRequest$inboundSchema: z.ZodType<
  GetPropertiesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  objectType: ObjectType$inboundSchema,
});
/** @internal */
export type GetPropertiesRequest$Outbound = {
  objectType: string;
};

/** @internal */
export const GetPropertiesRequest$outboundSchema: z.ZodType<
  GetPropertiesRequest$Outbound,
  z.ZodTypeDef,
  GetPropertiesRequest
> = z.object({
  objectType: ObjectType$outboundSchema,
});

export function getPropertiesRequestToJSON(
  getPropertiesRequest: GetPropertiesRequest,
): string {
  return JSON.stringify(
    GetPropertiesRequest$outboundSchema.parse(getPropertiesRequest),
  );
}
export function getPropertiesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPropertiesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPropertiesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPropertiesRequest' from JSON`,
  );
}

/** @internal */
export const GetPropertiesResponse$inboundSchema: z.ZodType<
  GetPropertiesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([z.record(z.any()), b64$.zodInbound]);
/** @internal */
export type GetPropertiesResponse$Outbound = { [k: string]: any } | Uint8Array;

/** @internal */
export const GetPropertiesResponse$outboundSchema: z.ZodType<
  GetPropertiesResponse$Outbound,
  z.ZodTypeDef,
  GetPropertiesResponse
> = z.union([z.record(z.any()), b64$.zodOutbound]);

export function getPropertiesResponseToJSON(
  getPropertiesResponse: GetPropertiesResponse,
): string {
  return JSON.stringify(
    GetPropertiesResponse$outboundSchema.parse(getPropertiesResponse),
  );
}
export function getPropertiesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPropertiesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPropertiesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPropertiesResponse' from JSON`,
  );
}
