/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SearchCompaniesResponse =
  | components.CollectionResponseWithTotalSimplePublicObjectForwardPaging
  | Uint8Array
  | string;

/** @internal */
export const SearchCompaniesResponse$inboundSchema: z.ZodType<
  SearchCompaniesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components
    .CollectionResponseWithTotalSimplePublicObjectForwardPaging$inboundSchema,
  b64$.zodInbound,
]);
/** @internal */
export type SearchCompaniesResponse$Outbound =
  | components.CollectionResponseWithTotalSimplePublicObjectForwardPaging$Outbound
  | Uint8Array;

/** @internal */
export const SearchCompaniesResponse$outboundSchema: z.ZodType<
  SearchCompaniesResponse$Outbound,
  z.ZodTypeDef,
  SearchCompaniesResponse
> = z.union([
  components
    .CollectionResponseWithTotalSimplePublicObjectForwardPaging$outboundSchema,
  b64$.zodOutbound,
]);

export function searchCompaniesResponseToJSON(
  searchCompaniesResponse: SearchCompaniesResponse,
): string {
  return JSON.stringify(
    SearchCompaniesResponse$outboundSchema.parse(searchCompaniesResponse),
  );
}
export function searchCompaniesResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchCompaniesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchCompaniesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchCompaniesResponse' from JSON`,
  );
}
