/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SearchDealsResponse =
  | components.CollectionResponseWithTotalSimplePublicObjectForwardPaging
  | Uint8Array
  | string;

/** @internal */
export const SearchDealsResponse$inboundSchema: z.ZodType<
  SearchDealsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components
    .CollectionResponseWithTotalSimplePublicObjectForwardPaging$inboundSchema,
  b64$.zodInbound,
]);

/** @internal */
export type SearchDealsResponse$Outbound =
  | components.CollectionResponseWithTotalSimplePublicObjectForwardPaging$Outbound
  | Uint8Array;

/** @internal */
export const SearchDealsResponse$outboundSchema: z.ZodType<
  SearchDealsResponse$Outbound,
  z.ZodTypeDef,
  SearchDealsResponse
> = z.union([
  components
    .CollectionResponseWithTotalSimplePublicObjectForwardPaging$outboundSchema,
  b64$.zodOutbound,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SearchDealsResponse$ {
  /** @deprecated use `SearchDealsResponse$inboundSchema` instead. */
  export const inboundSchema = SearchDealsResponse$inboundSchema;
  /** @deprecated use `SearchDealsResponse$outboundSchema` instead. */
  export const outboundSchema = SearchDealsResponse$outboundSchema;
  /** @deprecated use `SearchDealsResponse$Outbound` instead. */
  export type Outbound = SearchDealsResponse$Outbound;
}

export function searchDealsResponseToJSON(
  searchDealsResponse: SearchDealsResponse,
): string {
  return JSON.stringify(
    SearchDealsResponse$outboundSchema.parse(searchDealsResponse),
  );
}

export function searchDealsResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchDealsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchDealsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchDealsResponse' from JSON`,
  );
}
