/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AssociatedId = {
  id: string;
  type: string;
};

/** @internal */
export const AssociatedId$inboundSchema: z.ZodType<
  AssociatedId,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: z.string(),
});
/** @internal */
export type AssociatedId$Outbound = {
  id: string;
  type: string;
};

/** @internal */
export const AssociatedId$outboundSchema: z.ZodType<
  AssociatedId$Outbound,
  z.ZodTypeDef,
  AssociatedId
> = z.object({
  id: z.string(),
  type: z.string(),
});

export function associatedIdToJSON(associatedId: AssociatedId): string {
  return JSON.stringify(AssociatedId$outboundSchema.parse(associatedId));
}
export function associatedIdFromJSON(
  jsonString: string,
): SafeParseResult<AssociatedId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssociatedId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssociatedId' from JSON`,
  );
}
