/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ErrorDetail = {
  /**
   * A specific category that contains more specific detail about the error
   */
  subCategory?: string | undefined;
  /**
   * The status code associated with the error detail
   */
  code?: string | undefined;
  /**
   * The name of the field or parameter in which the error was found.
   */
  in?: string | undefined;
  /**
   * Context about the error condition
   */
  context?: { [k: string]: Array<string> } | undefined;
  /**
   * A human readable message describing the error along with remediation steps where appropriate
   */
  message: string;
};

/** @internal */
export const ErrorDetail$inboundSchema: z.ZodType<
  ErrorDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  subCategory: z.string().optional(),
  code: z.string().optional(),
  in: z.string().optional(),
  context: z.record(z.array(z.string())).optional(),
  message: z.string(),
});

/** @internal */
export type ErrorDetail$Outbound = {
  subCategory?: string | undefined;
  code?: string | undefined;
  in?: string | undefined;
  context?: { [k: string]: Array<string> } | undefined;
  message: string;
};

/** @internal */
export const ErrorDetail$outboundSchema: z.ZodType<
  ErrorDetail$Outbound,
  z.ZodTypeDef,
  ErrorDetail
> = z.object({
  subCategory: z.string().optional(),
  code: z.string().optional(),
  in: z.string().optional(),
  context: z.record(z.array(z.string())).optional(),
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorDetail$ {
  /** @deprecated use `ErrorDetail$inboundSchema` instead. */
  export const inboundSchema = ErrorDetail$inboundSchema;
  /** @deprecated use `ErrorDetail$outboundSchema` instead. */
  export const outboundSchema = ErrorDetail$outboundSchema;
  /** @deprecated use `ErrorDetail$Outbound` instead. */
  export type Outbound = ErrorDetail$Outbound;
}

export function errorDetailToJSON(errorDetail: ErrorDetail): string {
  return JSON.stringify(ErrorDetail$outboundSchema.parse(errorDetail));
}

export function errorDetailFromJSON(
  jsonString: string,
): SafeParseResult<ErrorDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorDetail' from JSON`,
  );
}
