/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Filter,
  Filter$inboundSchema,
  Filter$Outbound,
  Filter$outboundSchema,
} from "./filter.js";

export type FilterGroup = {
  filters: Array<Filter>;
};

/** @internal */
export const FilterGroup$inboundSchema: z.ZodType<
  FilterGroup,
  z.ZodTypeDef,
  unknown
> = z.object({
  filters: z.array(Filter$inboundSchema),
});
/** @internal */
export type FilterGroup$Outbound = {
  filters: Array<Filter$Outbound>;
};

/** @internal */
export const FilterGroup$outboundSchema: z.ZodType<
  FilterGroup$Outbound,
  z.ZodTypeDef,
  FilterGroup
> = z.object({
  filters: z.array(Filter$outboundSchema),
});

export function filterGroupToJSON(filterGroup: FilterGroup): string {
  return JSON.stringify(FilterGroup$outboundSchema.parse(filterGroup));
}
export function filterGroupFromJSON(
  jsonString: string,
): SafeParseResult<FilterGroup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FilterGroup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FilterGroup' from JSON`,
  );
}
