/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  NextPage,
  NextPage$inboundSchema,
  NextPage$Outbound,
  NextPage$outboundSchema,
} from "./nextpage.js";

export type ForwardPaging = {
  next?: NextPage | undefined;
};

/** @internal */
export const ForwardPaging$inboundSchema: z.ZodType<
  ForwardPaging,
  z.ZodTypeDef,
  unknown
> = z.object({
  next: NextPage$inboundSchema.optional(),
});
/** @internal */
export type ForwardPaging$Outbound = {
  next?: NextPage$Outbound | undefined;
};

/** @internal */
export const ForwardPaging$outboundSchema: z.ZodType<
  ForwardPaging$Outbound,
  z.ZodTypeDef,
  ForwardPaging
> = z.object({
  next: NextPage$outboundSchema.optional(),
});

export function forwardPagingToJSON(forwardPaging: ForwardPaging): string {
  return JSON.stringify(ForwardPaging$outboundSchema.parse(forwardPaging));
}
export function forwardPagingFromJSON(
  jsonString: string,
): SafeParseResult<ForwardPaging, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ForwardPaging$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ForwardPaging' from JSON`,
  );
}
