/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PublicObjectId = {
  id: string;
};

/** @internal */
export const PublicObjectId$inboundSchema: z.ZodType<
  PublicObjectId,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type PublicObjectId$Outbound = {
  id: string;
};

/** @internal */
export const PublicObjectId$outboundSchema: z.ZodType<
  PublicObjectId$Outbound,
  z.ZodTypeDef,
  PublicObjectId
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PublicObjectId$ {
  /** @deprecated use `PublicObjectId$inboundSchema` instead. */
  export const inboundSchema = PublicObjectId$inboundSchema;
  /** @deprecated use `PublicObjectId$outboundSchema` instead. */
  export const outboundSchema = PublicObjectId$outboundSchema;
  /** @deprecated use `PublicObjectId$Outbound` instead. */
  export type Outbound = PublicObjectId$Outbound;
}

export function publicObjectIdToJSON(publicObjectId: PublicObjectId): string {
  return JSON.stringify(PublicObjectId$outboundSchema.parse(publicObjectId));
}

export function publicObjectIdFromJSON(
  jsonString: string,
): SafeParseResult<PublicObjectId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicObjectId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicObjectId' from JSON`,
  );
}
