/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PublicObjectId = {
  id: string;
};

/** @internal */
export const PublicObjectId$inboundSchema: z.ZodType<
  PublicObjectId,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type PublicObjectId$Outbound = {
  id: string;
};

/** @internal */
export const PublicObjectId$outboundSchema: z.ZodType<
  PublicObjectId$Outbound,
  z.ZodTypeDef,
  PublicObjectId
> = z.object({
  id: z.string(),
});

export function publicObjectIdToJSON(publicObjectId: PublicObjectId): string {
  return JSON.stringify(PublicObjectId$outboundSchema.parse(publicObjectId));
}
export function publicObjectIdFromJSON(
  jsonString: string,
): SafeParseResult<PublicObjectId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicObjectId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicObjectId' from JSON`,
  );
}
