/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ValueWithTimestamp,
  ValueWithTimestamp$inboundSchema,
  ValueWithTimestamp$Outbound,
  ValueWithTimestamp$outboundSchema,
} from "./valuewithtimestamp.js";

export type SimplePublicObject = {
  createdAt: Date;
  archived?: boolean | undefined;
  archivedAt?: Date | undefined;
  propertiesWithHistory?:
    | { [k: string]: Array<ValueWithTimestamp> }
    | undefined;
  id: string;
  properties: { [k: string]: string | null };
  updatedAt: Date;
};

/** @internal */
export const SimplePublicObject$inboundSchema: z.ZodType<
  SimplePublicObject,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  archived: z.boolean().optional(),
  archivedAt: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  propertiesWithHistory: z.record(z.array(ValueWithTimestamp$inboundSchema))
    .optional(),
  id: z.string(),
  properties: z.record(z.nullable(z.string())),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

/** @internal */
export type SimplePublicObject$Outbound = {
  createdAt: string;
  archived?: boolean | undefined;
  archivedAt?: string | undefined;
  propertiesWithHistory?:
    | { [k: string]: Array<ValueWithTimestamp$Outbound> }
    | undefined;
  id: string;
  properties: { [k: string]: string | null };
  updatedAt: string;
};

/** @internal */
export const SimplePublicObject$outboundSchema: z.ZodType<
  SimplePublicObject$Outbound,
  z.ZodTypeDef,
  SimplePublicObject
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  archived: z.boolean().optional(),
  archivedAt: z.date().transform(v => v.toISOString()).optional(),
  propertiesWithHistory: z.record(z.array(ValueWithTimestamp$outboundSchema))
    .optional(),
  id: z.string(),
  properties: z.record(z.nullable(z.string())),
  updatedAt: z.date().transform(v => v.toISOString()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SimplePublicObject$ {
  /** @deprecated use `SimplePublicObject$inboundSchema` instead. */
  export const inboundSchema = SimplePublicObject$inboundSchema;
  /** @deprecated use `SimplePublicObject$outboundSchema` instead. */
  export const outboundSchema = SimplePublicObject$outboundSchema;
  /** @deprecated use `SimplePublicObject$Outbound` instead. */
  export type Outbound = SimplePublicObject$Outbound;
}

export function simplePublicObjectToJSON(
  simplePublicObject: SimplePublicObject,
): string {
  return JSON.stringify(
    SimplePublicObject$outboundSchema.parse(simplePublicObject),
  );
}

export function simplePublicObjectFromJSON(
  jsonString: string,
): SafeParseResult<SimplePublicObject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimplePublicObject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimplePublicObject' from JSON`,
  );
}
